language: node_js
node_js:
- 0.1
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd app
- npm install -g karma
- npm install -g karma-cli
- npm install -g bower
- bower install
- node ./scripts/web-server.js &
after_script:
- ps -ef | grep node | awk '{print $2}' | xargs kill -9
branches:
  only:
  - develop
notifications:
  email:
    recipients:
    - kydol37@gmail.com
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: DMaGbIkll5GseSxD8RWKiyXSj2so/rhyYrlrFuQHyW4CiKx66MWO78gcbVnW+uBN5sHfdOoopABvFW1e7Lb749NvZvF9SRDAj+IKEV3aYXmSKnjI09WlFhih8nNUzDE/1ry+kCsxYYqMmHL0CIiGrxtP5htq55s9EDo6PtGnZTY=
  app: ratior-staging
  on:
    repo: kydol37/kydol37.ratior.ui.web
    branch: develop
