language: node_js
node_js:
- 0.1
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd app
- npm install -g karma
- npm install -g karma-cli
- npm install -g bower
- bower install
- node ./scripts/web-server.js &
after_script:
- ps -ef | grep node | awk '{print $2}' | xargs kill -9
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: ANTs3xV2anBKvMAAvk9lfU5s7SJXuET/iwZDYiUUMTlKWgFO6p8RjSrw9oeE+LC1Zt2C5uxrYcrPzBzHTkStamW5rxLbScUq43+f3quDbSFxAd2L2Typm2Uah4LhwfC989F1yRjJYdrcjSNc6sF2WklU/PwYqECxDcbw/nmHpuE=
  app: ratior-staging
  on:
    repo: kydol37/kydol37.ratior.ui.web
    branch: develop
notifications:
  email:
    recipients:
    - kydol37@gmail.com
    on_success: change
    on_failure: always
