language: node_js
node_js:
- 0.1
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd app
- npm install -g karma
- npm install -g karma-cli
- npm install -g bower
- bower install
- node ./scripts/web-server.js
branches:
  only:
  - develop
deploy:
  provider: heroku
  api_key:
    secure: Tms3OHEgiYiXHnNAHb+y+UqraNzTSgti1vTSkjbJNAJJi78XkC+vOyvGrkUYJwYNkLzwHhKRR76GIgEo5TZQliSDWPM173en+7zNyKHq6vSMB5e1k4jw1oZPb0r4gJ5Cnd/zDtE3hINTmOlMfEYtThVDzrExaZKNMeR+kyaRRGE=
  app: 
    develop: ratior-staging
notifications:
  email:
    recipients:
    - kydol37@gmail.com
    on_success: change
    on_failure: always
