language: node_js
node_js:
  - 0.10

before_script:
  - cd app
  - npm install -g bower
  - bower install
  
branches:
  only:
    - develop

deploy:
  provider: heroku
  api_key:
    secure: Wj+Bo0rMTbpgPT4K2glFfdo1HnuoVNKqJeUp2UM4Adc0M2ojqwcbdu06393mVKYFAGQ5rHpYqzZDaurZdBaI78HkIkWguujb8cdqTi3JHf/LLwWiIVUVmzy9dt+SMZGX3G7xZhoG1HgAn0bbCdmVlal4ubJm+z31D2WKLIHqhSs=
  app: 
    ratior-staging
  
notifications:
  email:
    recipients:
      - kydol37@gmail.com
    on_success: change
    on_failure: always
    